apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: second-pipelinerun-
spec:
  params:
  - name: applnName
    value: "Value reassigned from pipelinerun second-pipeline"
  pipelineRef: 
    name: second-pipeline 
